password = 'mhjopdvzepgdjqaz'

LUDENTROP = 'm.ludentrop@gmail.com'
MAIER = 'agamemnonagross@gmail.com'
MAIR = 'mair24102001@gmail.com'
SUCCESS = 'successlife@gmail.com'
MAIRBEK = 'mairbek24102001@gmail.com'
ASVALD = 'asmatem12@gmail.com'
AXE = 'axe.capital52@gmail.com'
AMOLLOMA = 'amolloma69@outlook.com'
